import React, { useState, useEffect } from 'react';
import { User, Event, Invitation, UserRole, Partner } from '../types';
import { getEvents, getInvitations, createInvitation, deleteInvitation, getPartners } from '../services/mockBackend';
import { Plus, Edit2, Trash2, Smartphone, Monitor, ArrowRight, Building2, Calendar, FilePlus } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

interface InvitationManagerProps {
    user: User;
}

const InvitationManager: React.FC<InvitationManagerProps> = ({ user }) => {
    const navigate = useNavigate();
    const [events, setEvents] = useState<Event[]>([]);
    const [invitations, setInvitations] = useState<Invitation[]>([]);
    const [partners, setPartners] = useState<Partner[]>([]);
    const [selectedEventId, setSelectedEventId] = useState<string | null>(null);
    const [isCreating, setIsCreating] = useState(false);
    
    // New Invitation Form - Removed 'name' from state as it's now auto-generated
    const [newInvData, setNewInvData] = useState({ type: 'dynamic' as 'dynamic' | 'web' });

    useEffect(() => {
        const partnerIds = user.role === UserRole.SUPER_ADMIN ? undefined : user.partnerIds;
        getEvents(partnerIds).then(setEvents);
        getPartners().then(setPartners);
    }, [user]);

    useEffect(() => {
        if (selectedEventId) {
            // Load invitations for this specific event
            getInvitations(undefined, selectedEventId).then(setInvitations);
        } else {
            setInvitations([]);
        }
    }, [selectedEventId]);

    const handleCreateInvitation = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!selectedEventId) return;

        const event = events.find(e => e.id === selectedEventId);
        if (!event) return;

        // Auto-generate name based on Event + Type
        // e.g. "Smith Wedding (Mobile)" or "Smith Wedding (Web)"
        const autoGeneratedName = `${event.name} (${newInvData.type === 'dynamic' ? 'Mobile' : 'Web'})`;

        try {
            const newInv = await createInvitation({
                eventId: event.id,
                partnerId: event.partnerId,
                name: autoGeneratedName,
                type: newInvData.type,
                status: 'draft',
                content: { scenes: [] } // Initialize empty content
            });
            
            // Redirect immediately to the appropriate builder
            navigate(`/builder/${newInvData.type}/${newInv.id}`);
        } catch (err) {
            console.error("Failed to create invitation", err);
            alert("Failed to create invitation");
        }
    };

    const handleDeleteInvitation = async (id: string) => {
        if (window.confirm("Are you sure you want to delete this invitation?")) {
            await deleteInvitation(id);
            setInvitations(prev => prev.filter(i => i.id !== id));
        }
    };

    const handleEditInvitation = (inv: Invitation) => {
        navigate(`/builder/${inv.type}/${inv.id}`);
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center">
                <div>
                    <h2 className="text-2xl font-bold text-slate-800 dark:text-white">Invitation Manager</h2>
                    <p className="text-slate-500 dark:text-slate-400 text-sm">Select an event to manage its digital invitations.</p>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 h-[calc(100vh-180px)]">
                
                {/* 1. Event Selector List */}
                <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 overflow-hidden flex flex-col">
                    <div className="p-4 bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-700">
                        <h3 className="font-bold text-slate-700 dark:text-white text-sm uppercase tracking-wide">Available Events</h3>
                    </div>
                    <div className="flex-1 overflow-y-auto p-2 space-y-2 custom-scrollbar">
                        {events.length === 0 && (
                            <div className="p-4 text-center text-slate-400 text-sm">No events found. Create an event first.</div>
                        )}
                        {events.map(event => {
                            const partnerName = partners.find(p => p.id === event.partnerId)?.name;
                            const isSelected = selectedEventId === event.id;
                            
                            return (
                                <div 
                                    key={event.id}
                                    onClick={() => { setSelectedEventId(event.id); setIsCreating(false); }}
                                    className={`p-4 rounded-xl cursor-pointer transition-all border ${isSelected ? 'bg-indigo-50 dark:bg-indigo-900/20 border-indigo-500 ring-1 ring-indigo-500' : 'bg-white dark:bg-slate-800 border-slate-100 dark:border-slate-700 hover:border-indigo-300 dark:hover:border-indigo-700'}`}
                                >
                                    <div className="flex justify-between items-start mb-1">
                                        <h4 className={`font-bold ${isSelected ? 'text-indigo-700 dark:text-indigo-300' : 'text-slate-700 dark:text-white'}`}>{event.name}</h4>
                                        <span className="text-[10px] bg-slate-100 dark:bg-slate-700 text-slate-500 px-2 py-0.5 rounded-full">{event.type}</span>
                                    </div>
                                    <div className="flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400 mb-1">
                                        <Calendar size={12} /> {event.date}
                                    </div>
                                    {partnerName && (
                                        <div className="flex items-center gap-2 text-xs text-slate-400 dark:text-slate-500">
                                            <Building2 size={12} /> {partnerName}
                                        </div>
                                    )}
                                </div>
                            );
                        })}
                    </div>
                </div>

                {/* 2. Invitation List & Actions */}
                <div className="lg:col-span-2 bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 flex flex-col relative overflow-hidden">
                    {selectedEventId ? (
                        <>
                            <div className="p-6 border-b border-slate-200 dark:border-slate-800 flex justify-between items-center bg-slate-50 dark:bg-slate-800/30">
                                <div>
                                    <h3 className="font-bold text-slate-800 dark:text-white text-lg">Event Invitations</h3>
                                    <p className="text-xs text-slate-500">Managing invitations for <span className="font-semibold text-indigo-600 dark:text-indigo-400">{events.find(e => e.id === selectedEventId)?.name}</span></p>
                                </div>
                                {!isCreating && (
                                    <button 
                                        onClick={() => setIsCreating(true)} 
                                        className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition shadow-md"
                                    >
                                        <FilePlus size={18} /> Create New
                                    </button>
                                )}
                            </div>

                            <div className="flex-1 p-6 overflow-y-auto custom-scrollbar">
                                {isCreating ? (
                                    <div className="max-w-md mx-auto bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-6 shadow-sm animate-fade-in">
                                        <h4 className="text-lg font-bold text-slate-800 dark:text-white mb-4">Create New Invitation</h4>
                                        <form onSubmit={handleCreateInvitation} className="space-y-4">
                                            
                                            {/* Removed Name Input */}
                                            
                                            <div>
                                                <label className="block text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase mb-2">Invitation Format</label>
                                                <div className="grid grid-cols-2 gap-4">
                                                    <div 
                                                        onClick={() => setNewInvData({ ...newInvData, type: 'dynamic' })}
                                                        className={`cursor-pointer rounded-xl border-2 p-4 flex flex-col items-center gap-2 transition-all ${newInvData.type === 'dynamic' ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/20' : 'border-slate-200 dark:border-slate-700 hover:border-indigo-300'}`}
                                                    >
                                                        <Smartphone size={32} className={newInvData.type === 'dynamic' ? 'text-indigo-600 dark:text-indigo-400' : 'text-slate-400'} />
                                                        <span className={`text-sm font-bold ${newInvData.type === 'dynamic' ? 'text-indigo-700 dark:text-indigo-300' : 'text-slate-600 dark:text-slate-400'}`}>Dynamic (Mobile)</span>
                                                        <span className="text-[10px] text-center text-slate-500">Vertical, animated stories for phones.</span>
                                                    </div>
                                                    
                                                    <div 
                                                        onClick={() => setNewInvData({ ...newInvData, type: 'web' })}
                                                        className={`cursor-pointer rounded-xl border-2 p-4 flex flex-col items-center gap-2 transition-all ${newInvData.type === 'web' ? 'border-indigo-500 bg-indigo-50 dark:bg-indigo-900/20' : 'border-slate-200 dark:border-slate-700 hover:border-indigo-300'}`}
                                                    >
                                                        <Monitor size={32} className={newInvData.type === 'web' ? 'text-indigo-600 dark:text-indigo-400' : 'text-slate-400'} />
                                                        <span className={`text-sm font-bold ${newInvData.type === 'web' ? 'text-indigo-700 dark:text-indigo-300' : 'text-slate-600 dark:text-slate-400'}`}>Web (Responsive)</span>
                                                        <span className="text-[10px] text-center text-slate-500">Standard website format for all devices.</span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div className="flex gap-3 pt-2">
                                                <button type="button" onClick={() => setIsCreating(false)} className="flex-1 py-2.5 rounded-lg border border-slate-300 dark:border-slate-600 text-slate-600 dark:text-slate-300 font-medium hover:bg-slate-50 dark:hover:bg-slate-700">Cancel</button>
                                                <button type="submit" className="flex-1 py-2.5 rounded-lg bg-indigo-600 text-white font-bold hover:bg-indigo-700 shadow-md">Create & Design</button>
                                            </div>
                                        </form>
                                    </div>
                                ) : (
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                        {invitations.length === 0 && <p className="col-span-full text-center text-slate-400 py-10">No invitations created yet.</p>}
                                        {invitations.map(inv => (
                                            <div key={inv.id} className="group bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-4 hover:shadow-lg transition-all relative overflow-hidden">
                                                <div className="absolute top-0 right-0 p-2 opacity-0 group-hover:opacity-100 transition-opacity flex gap-1 bg-white/80 dark:bg-slate-900/80 backdrop-blur-sm rounded-bl-xl">
                                                    <button onClick={() => handleEditInvitation(inv)} className="p-1.5 bg-indigo-100 text-indigo-600 rounded-lg hover:bg-indigo-200" title="Edit Design"><Edit2 size={16}/></button>
                                                    <button onClick={() => handleDeleteInvitation(inv.id)} className="p-1.5 bg-red-100 text-red-600 rounded-lg hover:bg-red-200" title="Delete"><Trash2 size={16}/></button>
                                                </div>
                                                
                                                <div className="flex items-center gap-3 mb-3">
                                                    <div className={`p-2 rounded-lg ${inv.type === 'dynamic' ? 'bg-purple-100 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400' : 'bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400'}`}>
                                                        {inv.type === 'dynamic' ? <Smartphone size={20} /> : <Monitor size={20} />}
                                                    </div>
                                                    <div>
                                                        <h4 className="font-bold text-slate-800 dark:text-white text-sm">{inv.name}</h4>
                                                        <span className="text-[10px] text-slate-500 uppercase tracking-wider">{inv.type} Invitation</span>
                                                    </div>
                                                </div>
                                                
                                                <div className="flex justify-between items-center mt-4">
                                                    <span className={`text-[10px] px-2 py-0.5 rounded-full uppercase font-bold ${inv.status === 'published' ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{inv.status}</span>
                                                    <button onClick={() => handleEditInvitation(inv)} className="text-xs font-semibold text-indigo-600 dark:text-indigo-400 flex items-center gap-1 hover:underline">
                                                        Open Builder <ArrowRight size={12} />
                                                    </button>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                )}
                            </div>
                        </>
                    ) : (
                        <div className="flex-1 flex flex-col items-center justify-center text-slate-400">
                            <div className="w-16 h-16 bg-slate-100 dark:bg-slate-800 rounded-full flex items-center justify-center mb-4">
                                <Calendar size={32} className="opacity-50" />
                            </div>
                            <p className="font-medium">Please select an event from the left list</p>
                            <p className="text-sm opacity-70">to manage its invitations</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default InvitationManager;